name: "MD to DOCX"
description: 'Converts Markdown File to Docx Word Document'
inputs:
  input-name:
    description: 'Name of input file, must be a markdown file'
    required: true
  output-name:
    description: 'Name of output file'
    required: true
outputs:
  file:
    description: 'file generated'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-name }}
    - ${{ inputs.output-name }}
